# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"dotfolder": "00_core.ipynb",
         "ensure_dotfolder": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://turkishmaid.github.io/nbvalidate/"

git_url = "https://github.com/turkishmaid/nbvalidate/tree/master/"

def custom_doc_links(name): return None
