# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['dotfolder', 'ensure_dotfolder']

# Cell
import os
from pathlib import Path

# Cell
def dotfolder():
    return Path(os.environ["HOME"]) / ".nbvalidate"

# Cell
def ensure_dotfolder():
    folder = dotfolder()
    if not folder.exists():
        folder.mkdir()
        return False
    return True